"""Add Widgets table

Revision ID: fadd69bfd241
Revises: 
Create Date: 2022-08-27 17:11:58.634115-04:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadd69bfd241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('number_of_parts', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('updated_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_table('widgets')
    # ### end Alembic commands ###
